networks:
  pdns:
    name: pdns
    driver: bridge
  traefik:
    name: traefik
    external: true

services:
  pdns_auth:
    container_name: pdns_auth
    restart: unless-stopped
    image: powerdns/pdns-auth-49
    env_file:
      - .env
    networks:
      pdns:
    ports:
      - 53:53
      - 53:53/udp
      - 8081:8081

  pdns:
    container_name: pdns
    restart: unless-stopped
    image: powerdnsadmin/pda-legacy:latest
    env_file:
      - .env
    networks:
      traefik:
    expose: 
      - 80
    volumes:
      - pda-data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.pdns.tls: true
      traefik.http.routers.pdns.tls.certresolver: production

  volumes:
    pda-data:
      external: true
      name: pda-data
